version:
  scheme: git_pep440
  number: "0.1.0"

search_patterns:
  setuppy: "(?<=version=\\\"){{ git_pep440 }}"

# Available replacements:
#   - major
#   - minor
#   - patch
#   - next_major
#   - next_minor
#   - next_patch
#   - dev
#   - next_dev
#   - post
#   - next_post
#   - pre
#   - next_pre
# replacement_patterns:
#   full: "{{ major }}.{{ minor }}.{{ patch }}1"

# defaults:
#   search: basic
#   replacement: full

files:
  - filename: setup.py
    replacements:
      - search: setuppy
        replace: full
