config: 1

version:
  scheme: pep440
  number: 1.2.1

search_patterns:
  setuppy: "(?<=version=\\\"){{ pep440 }}"

defaults:
  search: pep440
  replacement: full

groups:
  code: 'scd/.*?\.py'
  docs: "docs/.*?"

files:
  setup.py:
    - search: setuppy
      replace: full
  docs/source/conf.py:
    - search_raw: "(?<=version\\s=\\s'){{ pep440 }}"
      replace_raw: "{{ major }}.{{ minor }}"
    - search_raw: "(?<=^release\\s=\\s'){{ pep440 }}"
      replace_raw: "{{ major }}.{{ minor }}.{{ patch }}"
  scd/__init__.py:
    - search_raw: '(?<=^__version__\s=\s"){{ pep440 }}'
      replace_raw: "{{ major }}.{{ minor }}.{{ patch }}{% if post %}.post{{ post }}{% endif %}{% if dev %}.dev{{ dev }}{% endif %}"
