version:
  scheme: semver
  number: 0.1.0

search_patterns:
  basic: "\\d\\d\\d"
  advanced: "\\sdfas\\df\\sdf"

# Available replacements:
#   - major
#   - minor
#   - patch
#   - next_major
#   - next_minor
#   - next_patch
#   - dev
#   - next_dev
#   - post
#   - next_post
#   - pre
#   - next_pre
replacement_patterns:
  full: "{{ major }}.{{ minor }}.{{ patch }}"

defaults:
  search: basic
  replacement: full

files:
  - filename: setup.py
    replacements:
      - search: basic
        replace: major_minor
      - search_raw: "sadfsadfs"
        replace_raw: "sdfsdfsdfsdf"
